[pytest]
testpaths = tests
python_files = test_*.py
markers =
    is_unique
    check_permutation
    urlify
    string_compression
    rotate_matrix
    zero_matrix
    stack_min
    sort_stack
    sorted_merge
    search_rotated
    sorted_matrix_search
    peaks_valleys
    sorted_search_no_size
    rank_from_stream
